---
- name: create jazzroutine virtualenv
  command: "virtualenv -p /usr/bin/python3 {{ virtualenv_dir }}"

- name: install project python requirements
  pip: 
    requirements: "{{ project_dir }}/requirements.txt"
    virtualenv: "{{ virtualenv_dir }}"

- name: install gunicorn
  pip: 
    name: gunicorn
    version: 19.7.*
    virtualenv: "{{ virtualenv_dir }}"

- name: copy gunicorn upstart config
  become: yes
  template:
    src: upstart/gunicorn-jazzroutine.conf
    dest: /etc/init/gunicorn-jazzroutine.conf
    force: yes

- name: launch database from docker-compose 
  shell: "docker-compose -f {{ project_dir }}/docker/compose.dev.yml up -d" # TODO Use proper module

- name: copy nginx jazzroutine config
  become: yes
  copy:
    src: nginx/jazzroutine.conf
    dest: /etc/nginx/sites-available/jazzroutine.conf
    force: yes

- name: enable nginx jazzroutine config
  become: yes
  file:
    src: /etc/nginx/sites-available/jazzroutine.conf
    path: /etc/nginx/sites-enabled/jazzroutine.conf
    state: link

- name: create nginx ssl directory
  become: yes
  file:
    path: /etc/nginx/ssl
    state: directory

- name: create self signed SSL certificate
  become: yes
  command: >
    openssl req -x509 -nodes -days 365 
    -newkey rsa:2048 
    -keyout /etc/nginx/ssl/nginx.key 
    -out /etc/nginx/ssl/nginx.crt
    -subj "/C=US/ST=foo/L=bar/O=baz/CN=www.foo.com"

- name: restart gunicorn
  become: yes
  service:
    name: gunicorn-jazzroutine
    state: restarted

- name: restart nginx
  service: 
    name: nginx 
    state: restarted
