---
- hosts: all
  roles:
    - role: development
    - role: docker_engine
      docker_user: vagrant
    - role: docker_compose
    - role: jazz_routine
      project_dir: /workspace/projects/JazzRoutine
      virtualenv_dir: /home/vagrant/.virtualenvs/JazzRoutine
    - role: nginx
    - role: python
      virtual_env_user: vagrant
