---
- name: install python packages
  become: yes
  apt: 
    update_cache: yes 
    name: "{{ item }}" 
    state: present
  with_items:
   - build-essential
   - python
   - python3
   - python3-dev
   - python3-pip

- name: install virtualenv
  become: yes
  pip: 
    name: virtualenv
    state: present
