---
- name: install python packages
  become: yes
  apt: 
    update_cache: yes 
    name: "{{ item }}" 
    state: present
  with_items:
   - build-essential
   - python
   - python3
   - python3-dev
   - python3-pip

- name: install pip packages
  become: yes
  pip: 
    name: "{{ item }}"
    state: present
  with_items:
   - virtualenv
   - virtualenvwrapper

- name: determine virtualenv dir 
  set_fact:
     virtual_env_dir: "/home/{{ virtual_env_user }}/.virtualenvs"

- name: create virtualenv dir
  file:
    path: "{{ virtual_env_dir }}"
    state: directory
    mode: 0755

- name: determine shell used
  shell: "grep -E '^{{ virtual_env_user }}' /etc/passwd | cut -d ':' -f 7"
  register: shell_bin

- debug:
    var: shell_bin.stdout
    verbosity: 1

- name: determine shell profile file
  set_fact:
    profile_path: "/home/{{ virtual_env_user }}/{{ shell_profile_files[shell_bin.stdout] }}"

- debug:
    var: profile_path
    verbosity: 1

- name: set virtualenv environment variables
  lineinfile:
    path: "{{ profile_path }}"
    line: "{{ item }}"
    create: yes
  with_items:
   - "export WORKON_HOME={{ virtual_env_dir }}"
   - "export PROJECT_HOME={{ virtual_env_project_dir }}"
   - "source /usr/local/bin/virtualenvwrapper.sh"
