---
# Install Docker engine using install script

- name: download Docker installer
  get_url: 
    url: https://get.docker.com/
    dest: /tmp/docker-installer.sh

- name: give exec permissions to installer file 
  file:
    path: /tmp/docker-installer.sh
    mode: 0744

- name: run Docker installer
  command: /tmp/docker-installer.sh