---
# http://blog.alexellis.io/get-started-with-docker-on-64-bit-arm/

- name: install python-pip
  become: yes
  apt: 
    name: python-pip 
    state: present
    update_cache: yes 

- name: install docker-compose
  become: yes
  pip: 
    name: docker-compose
    state: present
    version: "{{ docker_compose_required_version }}"