---

- name: get Docker compose version
  command: docker-compose version --short
  register: docker_compose_current_version
  ignore_errors: yes

- name: print current Docker compose version
  debug: 
    var: docker_compose_current_version.stdout
    verbosity: 1

# Install only if not installed or current version different from the required one
- include: install.yml
  when: (docker_compose_current_version.stdout is undefined) or
        docker_compose_current_version.stdout | version_compare(docker_compose_version, '!=')